# Generated by Django 2.1 on 2018-09-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0003_auto_20180904_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Scan definition Date')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'ordering': ['date'],
            },
        ),
    ]
