# Generated by Django 2.1 on 2018-08-21 21:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Place definition Date')),
            ],
            options={
                'verbose_name': 'Place',
                'ordering': ['date'],
            },
        ),
    ]
