# Generated by Django 2.1 on 2018-08-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0002_place_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['date'], 'verbose_name': 'Place', 'verbose_name_plural': 'places'},
        ),
    ]
