# Generated by Django 2.1 on 2018-09-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocalisation', '0003_auto_20180828_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('id_station', models.IntegerField(max_length=1000)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Station definition Date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalisation.Place')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'places',
                'ordering': ['date'],
            },
        ),
    ]
