# Generated by Django 2.1 on 2018-09-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id_station',
        ),
    ]
